### ISSUE TITLE
ExtundeleteX Segfaults when attempting any recovery task

### ISSUE THREAD

**Issue by AbysmalBiscuit** [AbysmalBiscuit/ExtundeleteX#1]
The reason why ExtundeleteX Segfaults is due to a change in the e2fsprogs library that happened between versions 1.42.12 and 1.43.13

If anyone would like to contribute or has any suggestions as to how ExtundeleteX can be fixed I am very happy to accept PRs and any help. :)

I will post progress updates in this issue.

**Comment by AbysmalBiscuit** [comment]
It appears to work now, hence I'll close the issue.

**Comment by pixelherodev** [comment]
I just tested it out, and the bug appears to still be here.

```
sudo ./src/extundelete /dev/loop0 --restore-directory i
NOTICE: Extended attributes are not restored.
Loading filesystem metadata ... 29 groups loaded.
Loading journal descriptors ... Segmentation fault
```

**Comment by mar77i** [comment]
While `valgrind` memcheck reports various invalid writes and reads, I currently have the same problem, too.
```console
# src/extundelete --log warn,info,error /dev/mapper/home --restore-directory i
NOTICE: Extended attributes are not restored.
Loading filesystem metadata ... 1650 groups loaded.
Loading journal descriptors ... Segmentation fault (core dumped)
```
